[tool.poetry]
name = "site-bit-loader"
version = "0.1.0"
description = ""
authors = ["Weit145 <weit.dima@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.116.1"
pytest = "^8.4.2"
alembic = "^1.16.5"
uvicorn = {extras = ["standard"], version = "^0.35.0"}
pydantic = {extras = ["email"], version = "^2.11.7"}
sqlalchemy = {extras = ["asyncio"], version = "^2.0.43"}
aiosqlite = "^0.21.0"
pydantic-settings = "^2.10.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
black = "^25.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
